# Generated by Django 4.2.7 on 2023-11-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemMenu',
        ),
        migrations.DeleteModel(
            name='SubItemMenu',
        ),
    ]
