# Generated by Django 4.2.7 on 2023-11-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_itemmenu_subitemmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitemmenu',
            name='item_menu_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.itemmenu'),
        ),
    ]
