# Generated by Django 4.2.7 on 2023-11-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_remove_subitemmenu_item_menu_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
