# Generated by Django 4.2.7 on 2023-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
